name: Build
on:
  push:
    branches: [main]
  pull_request:
    paths:
      - 'pycdc/**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v5

      - name: Build
        if: matrix.os != 'windows-latest'
        run: |
          mkdir build
          cd build
          cmake ../pycdc
          cmake --build . --config Debug
          cmake --install .

      - name: Build (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          mkdir build
          cd build
          cmake -G "MinGW Makefiles" ../pycdc
          cmake --build . --config Debug
          cmake --install .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pyarmor-1shot-build-${{ matrix.os }}
          path: |
            oneshot
            README.md
            LICENSE
            pycdc/README-Decompyle++.markdown
            pycdc/LICENSE
